coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: false

ignore:
  - "**/consensus/testutil/**"

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

